Rwc2022
tue-robotics/ed_object_models pull request #104
Opened 2022-07-28 08:35 UTC by PetervDooren

2022-07-28 08:46 UTC, MatthijsBurgh requested changes
Please fix SDF version of:
Bed
Couch
Dinner_table
Pantry
Salon_table
Sink
Trashbin
Washing_machine

2022-07-28 08:48 UTC, MatthijsBurgh commented
Please make sure any specific changes have been reverted.

Greetings from Kata, Phuket, Thailand 🇹🇭

2022-10-01 09:16 UTC, PetervDooren commented
ignore the rwc2022 environment. The important changes are the human model, exit_rips_point in impuls and load to safe_load in the source directory.

2022-10-01 10:40 UTC, MatthijsBurgh approved these changes

2022-10-01 10:40 UTC, merged