Split the on_top_of virtual volume of couch to left and right
tue-robotics/ed_object_models pull request #119
Opened 2024-01-06 13:37 UTC by shanki98

This is to make sure when people sit for example: on the left side of the couch, the entire couch is not recognized as occupied. 
So I split the short couch and long couch volumes accordingly. The 'in_front_of' volume remains unchanged though.

2024-01-08 08:33 UTC, MatthijsBurgh commented
Don't split it, just add the new ones.

2024-01-08 08:34 UTC, MatthijsBurgh requested changes
Don't split it, just add the new ones. (Please in alphabetical order)

2024-01-16 19:43 UTC, shanki98 commented
Made changes as per @MatthijsBurgh

2024-01-16 19:59 UTC, MatthijsBurgh commented on models/impuls/couch_short/model.sdf
> +      <virtual_volume name="on_top_of_on_top_of_couch_short_left_vv">
```suggestion
    <link name="on_top_of_left">
      <virtual_volume name="on_top_of_left_vv">
```

2024-01-16 19:59 UTC, MatthijsBurgh commented on models/impuls/couch_short/model.sdf
> +      <virtual_volume name="on_top_of_on_top_of_couch_short_right_vv">
```suggestion
    <link name="on_top_of_right">
      <virtual_volume name="on_top_of_right_vv">
```

2024-01-16 20:00 UTC, MatthijsBurgh approved these changes

2024-01-16 20:09 UTC, merged