hotfix add valid operator waypoint
tue-robotics/ed_object_models pull request #84
Opened 2021-12-03 18:49 UTC by PetervDooren

Proper fix to this should be done in the action server. But in the meantime we need a working robot

2021-12-04 07:30 UTC, MatthijsBurgh requested changes
Actually there shouldn't be any operator predefined in the WM

2021-12-04 07:31 UTC, MatthijsBurgh requested changes
No need to give it a pose yet, I think

2021-12-04 09:14 UTC, PetervDooren commented
Yes, it shouldnt be predefined but fixing the bug in the action server will take time. Therefore this hotfix, to be removed later once the bug is fixed. 
The pose does need to be predefined. Currently it is not updated by the action server

2021-12-04 14:08 UTC, MatthijsBurgh commented
@PetervDooren I will test without a pose this weekend

2021-12-04 15:12 UTC, PetervDooren commented
@MatthijsBurgh tested last Friday and I can say that at the very least the predefined pose is not overwritten.

2021-12-05 22:14 UTC, MatthijsBurgh commented
Pose is needed
https://github.com/tue-robotics/ed/blob/3ce42e4898ae3677b043d9448a47210d0b676124/src/ed.cpp#L375-L376

2021-12-05 22:15 UTC, MatthijsBurgh commented on models/impuls/model.sdf
> +      <pose>2.0 1.0 0 0 0 0</pose>
```suggestion
      <pose>0 0 0 0 0 0</pose>
```

2021-12-05 22:16 UTC, MatthijsBurgh approved these changes
Just as a very dirty hotfix.

2021-12-06 08:03 UTC, PetervDooren commented
I fear that setting it at the origin will fail all the time. I set it next to the operator table so a demo will actually succeed

2021-12-06 09:34 UTC, MatthijsBurgh commented
> I fear that setting it at the origin will fail all the time. I set it next to the operator table so a demo will actually succeed

To my knowledge, it is set correctly at the time it is being used. But it needs to be in the WM, of the correct type and have a pose.
If the hack in the action_server is so bad that it needs to be at the correct spot. I don't even approve this PR.

2021-12-06 10:19 UTC, MatthijsBurgh approved these changes

2021-12-06 10:34 UTC, merged